spring.application.name=mediconnect-backend

# ==========================
# MySQL Database
# ==========================
spring.datasource.url=jdbc:mysql://localhost:3306/mediconnect
spring.datasource.username=root
spring.datasource.password=Devang@8877

# ==========================
# JPA / Hibernate
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================
# Server
# ==========================
server.port=8080


spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=devangsinghchauhan933@gmail.com
spring.mail.password=tcqg fnbf yetk yqgo

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true